// <auto-generated />
namespace ShopBridge.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedImageFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedImageFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202008241321126_addedImageFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
